apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sszombie-node
  name: sszombie-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sszombie-node
  template:
    metadata:
      labels:
        app: sszombie-node
    spec:
      containers:
        - image: gcr.io/$PROJECT_ID/sinmetal/sszombie/feature/id/22:60605d1308ff8d193b05aa14e3521319e72414af
          name: sszombie-node
          envFrom:
            - configMapRef:
                name: sszombie-config